name: sif-arset
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - beautifulsoup4
  - cartopy
  - contextily
  - geopandas
  - imageio
  - ipykernel
  - jupyter
  - matplotlib
  - netcdf4
  - notebook
  - numpy
  - pandas
  - pydap
  - python-dotenv
  - rasterio
  - rasterstats
  - requests
  - requests-cache
  - scikit-learn
  - tqdm